name: deploy-web
on:
  push:
    branches:
      - main
jobs:
  build-emulator:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to web server
        run: |
          cp ./src/public/test.html /var/www/html/index.html
          cp -r ./dist /var/www/html/