name: deploy-web
on:
  push:
    branches:
      - main
jobs:
  build-emulator:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - run: npm install
        working-directory: ./src
      - run: npm run build
        working-directory: ./src
      - run: cp ./src/test.html /var/www/html/index.html
      - run: cp -r ./src/dist /var/www/html/dist